//
//  DeviceAttestationRequests.swift
//  Frame-iOS
//
//  Created by Frame Payments on 4/14/26.
//

import Foundation

/// Request body and response model namespace for Device Attestation API calls.
///
/// Encapsulates the request and response types used when registering and verifying
/// device attestations via the Frame SDK's attestation endpoints.
public class DeviceAttestationRequests {

    /// Request body sent to the attestation endpoint to register a device key.
    public struct AttestRequest: Encodable {
        /// The identifier of the device key generated by the App Attest service.
        let keyId: String
        /// The Base64-encoded attestation object returned by the App Attest service.
        let attestationObject: String
        /// The server-issued challenge that was used during key attestation.
        let challenge: String

        enum CodingKeys: String, CodingKey {
            case keyId = "key_id"
            case attestationObject = "attestation_object"
            case challenge
        }
    }

    /// Response model containing the server-issued challenge for device attestation.
    public struct ChallengeResponse: Decodable {
        /// The one-time challenge string issued by the server to be used during attestation.
        public let challenge: String
    }

    /// Response model returned after a successful device attestation registration.
    public struct AttestResponse: Decodable {
        /// The result status of the attestation request (e.g., `"success"`).
        public let status: String
        /// The key identifier that was registered with the server.
        public let keyId: String

        enum CodingKeys: String, CodingKey {
            case status
            case keyId = "key_id"
        }
    }
}
