#!/usr/bin/env python3
"""Generate (or verify) docs/SDK_MAP.md from the public surface of Sources/.

The map is generated output: everything between the AUTOGEN markers is rebuilt
from source on every run. Prose outside those markers is preserved verbatim, so
hand-written analysis survives regeneration.

Usage:
    generate_sdk_map.py            # rewrite docs/SDK_MAP.md in place
    generate_sdk_map.py --check    # exit 1 if the map is out of date (no write)
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(REPO_ROOT, "Sources")
MAP_PATH = os.path.join(REPO_ROOT, "docs", "SDK_MAP.md")

BEGIN = "<!-- BEGIN AUTOGENERATED SDK MAP -->"
END = "<!-- END AUTOGENERATED SDK MAP -->"

# Declaration modifiers that may appear between `public` and the keyword.
_MODS = r"(?:final|static|class|mutating|nonmutating|override|convenience|required|lazy|weak|unowned|indirect|dynamic|optional|nonisolated|consuming|borrowing|distributed)"
# `nonisolated(unsafe)` and similar parameterised modifiers.
_MODS_PAREN = rf"(?:{_MODS}(?:\([^)]*\))?)"

DECL_RE = re.compile(
    rf"^(?P<indent>[ \t]*)"
    rf"(?:(?:@\w+(?:\([^)]*\))?\s+)*)"          # leading attributes on the same line
    rf"(?P<access>public|open)\s+"
    rf"(?P<mods>(?:{_MODS_PAREN}\s+)*)"
    rf"(?P<kind>class|struct|enum|protocol|actor|typealias|extension|func|var|let|init|subscript)\b"
    rf"(?P<rest>.*)$"
)

# `case` inside a public enum is public but carries no access keyword.
CASE_RE = re.compile(r"^(?P<indent>[ \t]*)case\s+(?P<rest>[A-Za-z_].*)$")

TYPE_KINDS = {"class", "struct", "enum", "protocol", "actor"}



@dataclass
class Symbol:
    kind: str
    name: str
    signature: str
    file: str
    line: int
    container: str = ""

    @property
    def qualified(self) -> str:
        return f"{self.container}.{self.name}" if self.container else self.name




def _name_from_rest(kind: str, rest: str) -> str:
    rest = rest.strip()
    if kind == "init":
        return "init"
    if kind == "subscript":
        return "subscript"
    m = re.match(r"[`]?([A-Za-z_][A-Za-z0-9_]*)[`]?", rest)
    return m.group(1) if m else rest[:40]


def _signature(kind: str, name: str, rest: str) -> str:
    """A compact, readable one-line rendering of the declaration."""
    rest = rest.strip()
    # Drop a trailing body brace and anything after it.
    brace = rest.find("{")
    if brace != -1:
        rest = rest[:brace].strip()
    rest = re.sub(r"\s+", " ", rest).rstrip()
    if kind in ("func", "init", "subscript"):
        return f"{kind} {rest}" if kind != "func" else f"func {rest}"
    if kind in ("var", "let"):
        return f"{kind} {rest}"
    return f"{kind} {rest}" if rest else kind


def _strip_comments_and_strings(text: str) -> str:
    """Blank out string literals and comments so brace counting is reliable.

    Newlines are preserved so line numbers stay correct.
    """
    out = []
    i, n = 0, len(text)
    state = None  # None | 'line' | 'block' | 'str' | 'rawstr'
    depth = 0
    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if state is None:
            if c == "/" and nxt == "/":
                state = "line"; out.append("  "); i += 2; continue
            if c == "/" and nxt == "*":
                state = "block"; depth = 1; out.append("  "); i += 2; continue
            if c == '"':
                # Raw string?  #"..."#
                if out and out[-1] == "#":
                    state = "rawstr"
                else:
                    state = "str"
                out.append(" "); i += 1; continue
            out.append(c); i += 1; continue
        if state == "line":
            if c == "\n":
                state = None; out.append("\n")
            else:
                out.append(" ")
            i += 1; continue
        if state == "block":
            if c == "/" and nxt == "*":
                depth += 1; out.append("  "); i += 2; continue
            if c == "*" and nxt == "/":
                depth -= 1; out.append("  "); i += 2
                if depth == 0:
                    state = None
                continue
            out.append("\n" if c == "\n" else " "); i += 1; continue
        # inside a string
        if c == "\\" and state == "str":
            out.append("  "); i += 2; continue
        if c == '"':
            state = None
        out.append("\n" if c == "\n" else " ")
        i += 1
    return "".join(out)


@dataclass
class Scope:
    """One open brace scope while walking a file."""
    depth: int          # brace depth at which this scope was opened
    name: str           # qualified type name, or "" for non-type scopes
    kind: str           # "enum" | "struct" | "class" | "protocol" | "actor" | "extension" | "block"
    public: bool        # whether members declared here can be part of the public API


# Any scope-opening declaration, regardless of access level.
ANY_DECL_RE = re.compile(
    rf"^[ \t]*(?:(?:@\w+(?:\([^)]*\))?\s+)*)"
    rf"(?P<access>private|fileprivate|internal|package|public|open)?\s*"
    rf"(?:{_MODS_PAREN}\s+)*"
    rf"(?P<kind>class|struct|enum|protocol|actor|extension|func|init|subscript|var|let)\b"
    rf"(?P<rest>.*)$"
)

# Serialization plumbing, not API surface: `CodingKeys` cases are an
# implementation detail of Codable conformance and are never called by an
# integrator, so they are excluded from the map.
EXCLUDED_TYPE_NAMES = {"CodingKeys"}


def parse_file(path: str) -> list[Symbol]:
    """Extract every public declaration from one Swift file.

    Walks the file line by line tracking brace scopes. A declaration counts as
    public when it is written `public`/`open` *and* every enclosing type scope
    is itself public -- a public func inside a private struct is not reachable
    and so is not part of the surface.
    """
    with open(path, "r", encoding="utf-8") as fh:
        raw = fh.read()
    # Comments and string literals are blanked (newlines preserved) so that
    # braces inside them never move the depth counter.
    lines = _strip_comments_and_strings(raw).split("\n")

    rel = os.path.relpath(path, REPO_ROOT)
    symbols: list[Symbol] = []
    stack: list[Scope] = []
    depth = 0

    for idx, line in enumerate(lines):
        opens = line.count("{") - line.count("}")

        def enclosing_public() -> bool:
            return all(sc.public for sc in stack if sc.kind != "block")

        def container() -> str:
            for sc in reversed(stack):
                if sc.kind == "block":
                    return ""      # inside a function body: not a declaration site
                if sc.name:
                    return sc.name
            return ""

        m = DECL_RE.match(line)
        if m:
            kind, rest = m.group("kind"), m.group("rest")
            # A declaration whose parameter list wraps across lines would
            # otherwise be recorded truncated at the first newline. The full
            # signature is what distinguishes two overloads from each other in
            # the map and in the drift diff, so pull in continuation lines until
            # the parentheses balance.
            if kind in ("func", "init", "subscript"):
                rest = _join_declaration(lines, idx, rest)
            name = _name_from_rest(kind, rest)
            excluded = name in EXCLUDED_TYPE_NAMES
            visible = enclosing_public() and not excluded

            if kind == "extension":
                # Not a symbol itself; members inside are attributed to the
                # extended type. A public extension of a public type keeps its
                # members public.
                if opens > 0:
                    stack.append(Scope(depth, name, "extension", visible))
                    depth += opens
                    continue
            elif kind in TYPE_KINDS:
                if visible:
                    symbols.append(
                        Symbol(kind, name, _signature(kind, name, rest), rel, idx + 1, container())
                    )
                if opens > 0:
                    qualified = f"{container()}.{name}" if container() else name
                    stack.append(Scope(depth, qualified, kind, visible))
                    depth += opens
                    continue
            else:
                if visible:
                    symbols.append(
                        Symbol(kind, name, _signature(kind, name, rest), rel, idx + 1, container())
                    )
                if opens > 0:
                    # A body (func, or a computed property's accessors).
                    stack.append(Scope(depth, "", "block", visible))
                    depth += opens
                    continue
            depth += opens
            while stack and depth <= stack[-1].depth:
                stack.pop()
            continue

        # An enum case is public by virtue of its enum; it carries no keyword.
        # Only collect when the innermost scope is literally an enum, which
        # excludes `switch` cases (those sit inside a "block" scope).
        cm = CASE_RE.match(line)
        if cm and stack and stack[-1].kind == "enum":
            if stack[-1].public and enclosing_public():
                for part in _split_cases(cm.group("rest").strip()):
                    symbols.append(
                        Symbol("case", _name_from_rest("case", part), f"case {part.strip()}",
                               rel, idx + 1, stack[-1].name)
                    )
            depth += opens
            while stack and depth <= stack[-1].depth:
                stack.pop()
            continue

        # Non-public (or unannotated) scope openers still have to be tracked, or
        # their contents would be misattributed to the enclosing public type.
        if opens > 0:
            am = ANY_DECL_RE.match(line)
            if am:
                kind = am.group("kind")
                name = _name_from_rest(kind, am.group("rest"))
                is_public = (am.group("access") in ("public", "open")) and name not in EXCLUDED_TYPE_NAMES
                if kind in TYPE_KINDS:
                    qualified = f"{container()}.{name}" if container() else name
                    stack.append(Scope(depth, qualified, kind, is_public))
                elif kind == "extension":
                    # An extension with no access keyword does NOT restrict its
                    # members: `extension FrameObjects { public enum ... }` is the
                    # SDK's dominant namespacing idiom, and those enums are public
                    # API. Only an explicitly private/fileprivate extension seals
                    # what is inside it.
                    sealed = am.group("access") in ("private", "fileprivate")
                    stack.append(Scope(depth, name, "extension", not sealed))
                else:
                    stack.append(Scope(depth, "", "block", is_public))
            else:
                # A bare `{` block: `if`, `switch`, closure, `do`, ...
                stack.append(Scope(depth, "", "block", stack[-1].public if stack else True))

        depth += opens
        while stack and depth <= stack[-1].depth:
            stack.pop()

    return symbols


def _join_declaration(lines: list[str], idx: int, rest: str, max_lookahead: int = 40) -> str:
    """Append continuation lines until the declaration's parentheses balance."""
    if "(" not in rest:
        return rest
    depth = rest.count("(") - rest.count(")")
    if depth <= 0:
        return rest
    parts = [rest.rstrip()]
    for j in range(idx + 1, min(idx + 1 + max_lookahead, len(lines))):
        nxt = lines[j]
        parts.append(nxt.strip())
        depth += nxt.count("(") - nxt.count(")")
        if depth <= 0:
            break
    return " ".join(p for p in parts if p)


def _split_cases(body: str) -> list[str]:
    """Split `a, b, c` into parts, respecting parens/angle brackets."""
    parts, buf, par = [], [], 0
    for ch in body:
        if ch in "(<[":
            par += 1
        elif ch in ")>]":
            par -= 1
        if ch == "," and par == 0:
            parts.append("".join(buf)); buf = []
            continue
        buf.append(ch)
    if buf:
        parts.append("".join(buf))
    return [p for p in parts if p.strip()]


def collect() -> list[Symbol]:
    out: list[Symbol] = []
    for dirpath, _dirnames, filenames in os.walk(SOURCES):
        for fn in sorted(filenames):
            if fn.endswith(".swift"):
                out.extend(parse_file(os.path.join(dirpath, fn)))
    return out


MODULE_BLURB = {
    "Frame": "Core SDK: networking for every Frame API resource, checkout and cart UI, "
             "theming, validation, and the Apple Pay surface.",
    "FrameOnboarding": "Onboarding product: the capability-driven identity/payment "
                       "verification flow, its screens, and the onboarding-only APIs "
                       "(3DS, IDV, phone OTP, geocompliance).",
}

KIND_ORDER = ["class", "struct", "enum", "protocol", "actor", "typealias",
              "init", "func", "var", "let", "case", "subscript"]
KIND_LABEL = {
    "class": "Classes", "struct": "Structs", "enum": "Enums",
    "protocol": "Protocols", "actor": "Actors", "typealias": "Type aliases",
    "init": "Initializers", "func": "Methods", "var": "Properties (var)",
    "let": "Properties (let)", "case": "Enum cases", "subscript": "Subscripts",
}


def _module_of(rel_path: str) -> str:
    parts = rel_path.split(os.sep)
    return parts[1] if len(parts) > 2 and parts[0] == "Sources" else "Frame"


def _group_path(rel_path: str) -> str:
    """The directory a file sits in, relative to its module. Used as a section."""
    parts = rel_path.split(os.sep)
    if len(parts) <= 3:
        return "(root)"
    return os.sep.join(parts[2:-1])


def render(symbols: list[Symbol]) -> str:
    """Render the autogenerated portion of the map."""
    total = len(symbols)
    by_module: dict[str, list[Symbol]] = {}
    for s in symbols:
        by_module.setdefault(_module_of(s.file), []).append(s)

    kind_counts = {}
    for s in symbols:
        kind_counts[s.kind] = kind_counts.get(s.kind, 0) + 1

    out: list[str] = []
    w = out.append

    w(BEGIN)
    w("")
    w("<!-- Generated by scripts/generate_sdk_map.py. Do not edit by hand: this")
    w("     section is rebuilt from Sources/ on every push. Add commentary in the")
    w("     hand-written sections outside the AUTOGENERATED markers instead. -->")
    w("")
    w("## Public API inventory")
    w("")
    w(f"**{total} public symbols** across "
      f"{len({s.file for s in symbols})} files in {len(by_module)} modules.")
    w("")
    w("| Kind | Count |")
    w("|------|-------|")
    for k in KIND_ORDER:
        if kind_counts.get(k):
            w(f"| {KIND_LABEL[k]} | {kind_counts[k]} |")
    w(f"| **Total** | **{total}** |")
    w("")

    for module in sorted(by_module):
        syms = by_module[module]
        w(f"### `{module}` — {len(syms)} public symbols")
        w("")
        if module in MODULE_BLURB:
            w(MODULE_BLURB[module])
            w("")

        groups: dict[str, list[Symbol]] = {}
        for s in syms:
            groups.setdefault(_group_path(s.file), []).append(s)

        for group in sorted(groups):
            gsyms = groups[group]
            w(f"#### {group} ({len(gsyms)})")
            w("")
            by_file: dict[str, list[Symbol]] = {}
            for s in gsyms:
                by_file.setdefault(s.file, []).append(s)
            for fpath in sorted(by_file):
                fsyms = sorted(by_file[fpath], key=lambda s: s.line)
                w(f"<details><summary><code>{os.path.basename(fpath)}</code> "
                  f"— {len(fsyms)} symbols</summary>")
                w("")
                w(f"[`{fpath}`]({_link(fpath)})")
                w("")
                w("| Symbol | Kind | Declaration | Line |")
                w("|--------|------|-------------|------|")
                for s in fsyms:
                    w(f"| `{_md(s.qualified)}` | {s.kind} | `{_md(_trunc(s.signature))}` "
                      f"| [{s.line}]({_link(fpath)}#L{s.line}) |")
                w("")
                w("</details>")
                w("")
    w(END)
    return "\n".join(out)


def _link(rel_path: str) -> str:
    return "../" + rel_path.replace(os.sep, "/")


def _md(text: str) -> str:
    """Escape the characters that would break a markdown table cell."""
    return text.replace("|", "\\|")


def _trunc(sig: str, limit: int = 160) -> str:
    sig = sig.strip()
    return sig if len(sig) <= limit else sig[: limit - 1] + "…"


TEMPLATE = """# Frame iOS SDK Map

A complete map of the public surface of the Frame iOS SDK: every public type,
method, property, initializer, and enum case in `Sources/`.

The inventory below is **generated from source** by `scripts/generate_sdk_map.py`
and refreshed automatically by `.github/workflows/sdk-map.yml` on every push that
touches `Sources/`. If you add or remove a public symbol, the map updates itself —
there is nothing to keep in sync by hand.

Prose written outside the `AUTOGENERATED` markers is preserved across
regeneration, so architectural notes belong there.

## Module layout

| Module | Product | Purpose |
|--------|---------|---------|
| `Frame` | `Frame-iOS` | Networking for every API resource, checkout/cart UI, theming, validation, Apple Pay. |
| `FrameOnboarding` | `Frame-Onboarding` | Capability-driven onboarding flow, its screens, and onboarding-only APIs (3DS, IDV, phone OTP, geocompliance). |

`FrameOnboarding` depends on `Frame`; the reverse is not true.

## How to read the inventory

- Symbols are grouped by module, then by source directory, then by file.
- `Symbol` is the qualified name — `FrameObjects.Capabilities` means the type is
  nested inside (or declared in an extension on) `FrameObjects`.
- Members declared inside a non-public type are excluded: they are not reachable
  by an integrator even when marked `public`.
- `CodingKeys` enums are excluded as serialization plumbing rather than API.
- Overloads are listed separately and distinguished by their argument labels, so
  the paired async and completion-handler variants of a call both appear.

"""


def build_document(symbols: list[Symbol], previous: str | None) -> str:
    """Compose the full map, preserving any hand-written prose."""
    generated = render(symbols)
    if previous and BEGIN in previous and END in previous:
        head = previous[: previous.index(BEGIN)]
        tail = previous[previous.index(END) + len(END):]
        return head + generated + tail
    return TEMPLATE + generated + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the map is out of date; do not write")
    args = ap.parse_args()

    symbols = collect()
    symbols.sort(key=lambda s: (s.file, s.line, s.qualified))

    previous = None
    if os.path.exists(MAP_PATH):
        with open(MAP_PATH, "r", encoding="utf-8") as fh:
            previous = fh.read()

    document = build_document(symbols, previous)

    if args.check:
        if previous == document:
            print(f"✅ SDK map is up to date ({len(symbols)} public symbols).")
            return 0
        print("❌ SDK map is out of date. Run: python3 scripts/generate_sdk_map.py")
        if previous is not None:
            _print_symbol_diff(previous, document)
        return 1

    os.makedirs(os.path.dirname(MAP_PATH), exist_ok=True)
    with open(MAP_PATH, "w", encoding="utf-8") as fh:
        fh.write(document)
    changed = previous != document
    status = "updated" if changed else "unchanged"
    print(f"{'✏️' if changed else '✅'} docs/SDK_MAP.md {status} "
          f"({len(symbols)} public symbols).")
    return 0


# Symbol | Kind | Declaration — the declaration is part of the identity so that
# overloads (the SDK pairs an async and a completion-handler variant of most
# calls) are distinct entries. Without it, removing one overload would leave the
# other's name in the set and the diff would report no change at all.
_ROW_RE = re.compile(r"^\| `([^`]+)` \| (\w+) \| `(.*)` \|")


def _symbol_rows(document: str) -> set[str]:
    rows = set()
    for line in document.split("\n"):
        m = _ROW_RE.match(line)
        if m:
            rows.add(f"{m.group(2)} {m.group(1)}  {m.group(3)}")
    return rows


def _fmt_row(row: str, limit: int = 110) -> str:
    """Collapse a row key to one readable line for the console diff."""
    row = re.sub(r"\s+", " ", row).strip()
    return row if len(row) <= limit else row[: limit - 1] + "…"


def _print_symbol_diff(previous: str, current: str) -> None:
    """Show which symbols changed, so the failure is actionable on its own."""
    before, after = _symbol_rows(previous), _symbol_rows(current)
    added, removed = sorted(after - before), sorted(before - after)
    if added:
        print(f"\n  Added ({len(added)}):")
        for a in added[:40]:
            print(f"    + {_fmt_row(a)}")
        if len(added) > 40:
            print(f"    … and {len(added) - 40} more")
    if removed:
        print(f"\n  Removed ({len(removed)}):")
        for r in removed[:40]:
            print(f"    - {_fmt_row(r)}")
        if len(removed) > 40:
            print(f"    … and {len(removed) - 40} more")
    if not added and not removed:
        print("\n  (Symbol set unchanged; formatting or line numbers moved.)")


if __name__ == "__main__":
    sys.exit(main())
